language: c
sudo: false
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack


before_install:
    - .travis/travis_before_install.sh

install:
    - export PATH=$HOME/.local/bin:$PATH
    - .travis/travis_install.sh

env:
  - STACKOPTS=" --no-terminal"

script:
  - stack test

addons:
  apt:
    packages:
      - libgmp10
      - libgmp-dev
